title: "§e[§cS§4hudown§e]"
# title ui

content: ""
# content ui

button0: "§7|§9Shutown§7|"
button1: "§7|§gExit§7|"
# buttons ui

message: "§e[§cS§4hudown§e] §f- §2thank for use :)"
# message exit ui